### ISSUE TITLE
Population Size Discrepancies

### ISSUE THREAD

**Issue by ian-flores** [c2-d2/pr_mort_official#1]
Hello, 

I would like to know why on page 7 of the appendix, it says that the number used as a population size (3,030,307) to estimate the excess death, but the excess_est.R file, on line 39 uses 3,405,520. This yields different results for the excess death number. 

Thank You

**Comment by nish-kishore** [comment]
Hi Ian, 

3,406,520 is the population estimate for 2016 which is used along with the official death registry to calculate the death rate in 2016. This rate is what we compare to. Our code uses the estimated pop of 3,030,307 `weighted_pop_est` which is read in on line 10 and generated in line 36 of `table-s1.R`. 

Best,

Nishant

**Comment by davidkane9** [comment]
> which is read in on line 10 and generated in line 36 of table-s1.R

I think you mean excess_est.R, not table-S1.R

**Comment by nish-kishore** [comment]
The weighed pop in generated in table-s1. It is called into the estimate in
excess_est.R

**Comment by davidkane9** [comment]
Ah, I see. I misread the "and" before "generated."
