### ISSUE TITLE
Is the code to replicate Table S4 available?

### ISSUE THREAD

**Issue by davidkane9** [c2-d2/pr_mort_official#2]
The R scripts in the code/ directory allows me to replicate Tables S1, S2 and S3. But I don't see anything for Table S4. Perhaps I am looking in the wrong place? I am most interested in replicating the 14.31 [9.76, 18.86] estimate for the annual mortality rate post-Maria. My attempts to do so "by hand" have been unsuccessful so far.

**Comment by nish-kishore** [comment]
Hi David, the easiest way to do this will be to use the script for excess_est.R in the code directory, we will work on creating a direct script.

**Comment by davidkane9** [comment]
Thanks. This is enough info for me. I don't need the code for Table S4, so feel free to close this issue.
