### ISSUE TITLE
The deaths_official data frame has "Pop" as a character variable

### ISSUE THREAD

**Issue by davidkane9** [c2-d2/pr_mort_official#3]
I don't think it hurts anything, but this is probably not what you want. The mistake probably originates in /resources/deaths_official.csv, which I can't see. (And that is OK! I assume that the resources directory includes non-public data.)

**Comment by nish-kishore** [comment]
Thank's David, I've adjusted this and included the pop estimates from vintage 17 of the census bureau. We used these numbers for our estimates and they are represented in the same table as `Popv17`
