### ISSUE TITLE
Confidence interval definition

### ISSUE THREAD

**Issue by rnj0nes** [c2-d2/pr_mort_official#4]
I do believe the definition of a confidence interval is not technically correct: "has a 95% chance of including the actual death count." This particular CI either contains the population value or it does not. If the survey were repeated 100 times, 95 of those would contain the population value. So we may say we can be 95% confident the interval contains the population value. An excellent visualization of the issue around interpreting CIs at http://rpsychologist.com/d3/CI/

**Comment by rafalab** [comment]
The entire statement is "We implemented an approach that generates a confidence interval that has a 95% chance of including the actual death count." The approach includes taking a random sample and thus the confidence interval should be considered a random variable rather than a realization.
