### ISSUE TITLE
The state of the repository *at publication*

### ISSUE THREAD

**Issue by mkiang** [c2-d2/pr_mort_official#8]
This repository is changing constantly in response to questions and feedback from others; however, I think it's worth documenting (somewhere) the commit *at the time of publication* is: e43ffc43c2d1844a91e2570b1cb570cc27a6262d

You can browse the files of this repository and all its code/data/etc in this "original state" via 
https://github.com/c2-d2/pr_mort_official/tree/e43ffc43c2d1844a91e2570b1cb570cc27a6262d

**Comment by karel-brinda** [comment]
You can create a tag or even a release for that. Then people could easy load the version corresponding to the time of publication using something like `git checkout paper`.

**Comment by karel-brinda** [comment]
https://github.community/t5/How-to-use-Git-and-GitHub/Create-releases-for-old-commits/td-p/6466

**Comment by mkiang** [comment]
Thanks for pointing that out, @karel-brinda — will do.

**Comment by mkiang** [comment]
I've made a tag of the paper version and you can find it under [the releases tab](https://github.com/c2-d2/pr_mort_official/releases). It is called `paper` so the command in comment https://github.com/c2-d2/pr_mort_official/issues/8#issuecomment-397420559 should work as shown. @nish-kishore we should add a reference to the release page somewhere on the main README?
